PROJECT=""
SOURCE_ENV=""
SOURCE_REGION=""
SOURCE_PROFILE=""
SOURCE_TABLE_NAME=""
DESTINATION_REGION=""
DESTINATION_PROFILE=""
DESTINATION_TABLE_NAME=""

sh scanTableToJson/scanTableToJson.sh ${SOURCE_PROFILE} ${SOURCE_TABLE_NAME} ${DESTINATION_TABLE_NAME} ${SOURCE_REGION} ${PROJECT} ${SOURCE_ENV}
sh insertBatchData/insertBatchData.sh ${DESTINATION_PROFILE} ${SOURCE_ENV} ${DESTINATION_TABLE_NAME} ${DESTINATION_REGION} ${PROJECT}
