AWS_PROFILE= \
SOURCE_REGION= \
SOURCE_PROFILE= \
SOURCE_ENV= \
SOURCE_TABLE_NAME= \
DESTINATION_REGION= \
DESTINATION_PROFILE= \
DESTINATION_ENV= \
DESTINATION_TABLE_NAME= \
sh scanTableToJson/scanTableToJson.sh ${SOURCE_PROFILE} ${SOURCE_TABLE_NAME} ${DESTINATION_TABLE_NAME} ${SOURCE_REGION} \
sh insert-batch-data/insert.sh ${DESTINATION_PROFILE} ${DESTINATION_TABLE_NAME} ${DESTINATION_REGION}